// .deploy/scripts/generator.js
import fs from 'fs-extra';
import path from 'path';
import { logger } from './utils/logger.js';
import { DEPLOY_DIR, REMOTE_DIR } from './utils/constants.js';

export class Generator {
  constructor(projectRoot = process.cwd()) {
    this.projectRoot = projectRoot;
    this.outputDir = path.join(projectRoot, DEPLOY_DIR, REMOTE_DIR);
  }

  async generate(config) {
    logger.header('Generating deployment files');

    await fs.ensureDir(this.outputDir);

    await this.generateDockerfile(config);
    await this.generateNginxConfig(config);
    await this.generateEntrypoint(config);

    logger.success('All files generated');
  }

  async generateDockerfile(config) {
    logger.step('Generating Dockerfile...');

    const { project, deploy } = config;
    const lines = [];

    // Base image
    lines.push('# Generated by docker-deploy skill');
    lines.push('FROM nginx:alpine');
    lines.push('');

    // Install backend runtime if needed
    if (project.backend) {
      const runtime = this.getRuntimeInstall(project.backend);
      lines.push('# Backend runtime');
      lines.push(runtime);
      lines.push('');
    }

    // Copy frontend
    if (project.frontend) {
      lines.push('# Frontend static files');
      lines.push('COPY frontend/ /var/www/html/');
      lines.push('');
    }

    // Copy backend
    if (project.backend) {
      lines.push('# Backend application');
      const backendPath = this.getBackendPath(project.backend);
      lines.push(`COPY backend/${backendPath.file} ${backendPath.container}`);
      lines.push('');
    }

    // Logs directory
    lines.push('# Logs directory');
    lines.push('RUN mkdir -p /var/log/nginx');
    if (project.backend) {
      lines.push(`RUN mkdir -p ${this.getBackendLogDir(project.backend)}`);
    }
    lines.push('');

    // Nginx config
    lines.push('# Nginx configuration');
    lines.push('COPY nginx/nginx.conf /etc/nginx/nginx.conf');
    lines.push('');

    // Entrypoint
    lines.push('# Startup script');
    lines.push('COPY scripts/entrypoint.sh /entrypoint.sh');
    lines.push('RUN chmod +x /entrypoint.sh');
    lines.push('');

    // Expose and entrypoint
    lines.push('EXPOSE 80');
    lines.push('ENTRYPOINT ["/entrypoint.sh"]');

    const dockerfile = lines.join('\n');
    await fs.writeFile(path.join(this.outputDir, 'Dockerfile'), dockerfile);
    logger.success('Dockerfile generated');
  }

  getRuntimeInstall(backend) {
    const runtimes = {
      java: 'RUN apk add --no-cache openjdk17-jre-headless',
      node: 'RUN apk add --no-cache nodejs npm',
      python: 'RUN apk add --no-cache python3 py3-pip',
      go: '# Go binary - no runtime needed'
    };
    return runtimes[backend.runtime] || '';
  }

  getBackendPath(backend) {
    const paths = {
      java: { file: 'app.jar', container: '/var/app/jar/app.jar' },
      node: { file: '', container: '/var/app/node/' },
      python: { file: '', container: '/var/app/python/' },
      go: { file: 'app', container: '/var/app/go/app' }
    };
    return paths[backend.runtime] || paths.java;
  }

  getBackendLogDir(backend) {
    const dirs = {
      java: '/var/app/jar/logs',
      node: '/var/app/node/logs',
      python: '/var/app/python/logs',
      go: '/var/app/go/logs'
    };
    return dirs[backend.runtime] || '/var/app/logs';
  }

  async generateNginxConfig(config) {
    logger.step('生成 nginx.conf...');

    const { project } = config;
    const lines = [];

    lines.push('worker_processes auto;');
    lines.push('error_log /var/log/nginx/error.log warn;');
    lines.push('pid /var/run/nginx.pid;');
    lines.push('');
    lines.push('events {');
    lines.push('    worker_connections 1024;');
    lines.push('}');
    lines.push('');
    lines.push('http {');
    lines.push('    include /etc/nginx/mime.types;');
    lines.push('    default_type application/octet-stream;');
    lines.push('');
    lines.push('    log_format main \'$remote_addr - $remote_user [$time_local] "$request" \'');
    lines.push('                      \'$status $body_bytes_sent "$http_referer" \'');
    lines.push('                      \'"$http_user_agent" "$http_x_forwarded_for"\';');
    lines.push('');
    lines.push('    access_log /var/log/nginx/access.log main;');
    lines.push('');
    lines.push('    sendfile on;');
    lines.push('    tcp_nopush on;');
    lines.push('    keepalive_timeout 65;');
    lines.push('    gzip on;');
    lines.push('');
    lines.push('    server {');
    lines.push('        listen 80;');
    lines.push('        server_name localhost;');
    lines.push('');

    // Frontend static files
    if (project.frontend) {
      lines.push('        # Frontend static files');
      lines.push('        location / {');
      lines.push('            root /var/www/html;');
      lines.push('            index index.html;');
      lines.push('            try_files $uri $uri/ /index.html;');
      lines.push('        }');
      lines.push('');
    }

    // Proxy locations
    if (project.proxy) {
      lines.push('        # Backend proxy');
      for (const [proxyPath, proxyConfig] of Object.entries(project.proxy)) {
        const port = project.backend?.port || 8080;

        lines.push(`        location ${proxyPath} {`);
        lines.push(`            proxy_pass http://127.0.0.1:${port};`);
        lines.push('            proxy_set_header Host $host;');
        lines.push('            proxy_set_header X-Real-IP $remote_addr;');
        lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
        lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
        lines.push('        }');
        lines.push('');
      }
    }

    lines.push('    }');
    lines.push('}');

    const nginxConf = lines.join('\n');
    await fs.ensureDir(path.join(this.outputDir, 'nginx'));
    await fs.writeFile(path.join(this.outputDir, 'nginx', 'nginx.conf'), nginxConf);
    logger.success('nginx.conf 已生成');
  }

  async generateEntrypoint(config) {
    logger.step('生成 entrypoint.sh...');

    const { project } = config;

    const lines = [];

    lines.push('#!/bin/sh');
    lines.push('# Generated by docker-deploy skill');
    lines.push('');
    lines.push('set -e');
    lines.push('');

    // Backend startup
    if (project.backend) {
      lines.push('# Backend startup');
      const startupCmd = this.getBackendStartupCommand(project.backend);
      lines.push(startupCmd);
      lines.push('');
      lines.push('# Wait for backend to start');
      lines.push('sleep 5');
      lines.push('');
      lines.push('# Start Nginx');
      lines.push('echo "Starting Nginx..."');
      lines.push('nginx -g "daemon off;"');
    } else {
      lines.push('# Start Nginx');
      lines.push('echo "Starting Nginx..."');
      lines.push('nginx -g "daemon off;"');
    }

    const entrypoint = lines.join('\n');
    await fs.ensureDir(path.join(this.outputDir, 'scripts'));
    await fs.writeFile(path.join(this.outputDir, 'scripts', 'entrypoint.sh'), entrypoint);
    logger.success('entrypoint.sh 已生成');
  }

  getBackendStartupCommand(backend) {
    const commands = {
      java: `JVM_ARGS="\${JVM_ARGS:--Xmx512m -Xms256m}"
SPRING_PROFILE="\${SPRING_PROFILE:-prod}"

echo "Starting Java application..."
cd /var/app/jar
java $JVM_ARGS -jar app.jar --spring.profiles.active=$SPRING_PROFILE $EXTRA_ARGS &`,
      node: `echo "Starting Node.js application..."
cd /var/app/node
node index.js &`,
      python: `echo "Starting Python application..."
cd /var/app/python
python3 main.py &`,
      go: `echo "Starting Go application..."
cd /var/app/go
./app &`
    };

    return commands[backend.runtime] || commands.java;
  }
}
