// .deploy/scripts/generator.js
import fs from 'fs-extra';
import path from 'path';
import { logger } from './utils/logger.js';
import { DEPLOY_DIR, REMOTE_DIR } from './utils/constants.js';

/**
 * 设计原则 (Design Principles):
 *
 * 1. 本地构建优先 (Build Locally First):
 *    - 所有编译/打包操作必须在本地完成
 *    - Dockerfile 只负责复制已构建的产物，不执行任何编译命令
 *    - 这样做的好处：构建缓存友好、镜像更小、构建更快、CI/CD 更可控
 *
 * 2. 禁止在容器内编译 (No In-Container Compilation):
 *    - 禁止使用多阶段构建来编译代码 (如 FROM maven AS builder)
 *    - 禁止在 RUN 指令中执行 mvn/npm/gradle/go build 等编译命令
 *    - Dockerfile 只能包含：FROM, COPY, ENV, EXPOSE, ENTRYPOINT 等
 *
 * 3. 验证构建产物 (Verify Build Artifacts):
 *    - 生成 Dockerfile 前必须验证构建产物存在
 *    - 如果产物不存在，应该报错而不是尝试在容器内构建
 */

export class Generator {
  constructor(projectRoot = process.cwd()) {
    this.projectRoot = projectRoot;
    this.outputDir = path.join(projectRoot, DEPLOY_DIR, REMOTE_DIR);
  }

  async generate(config) {
    logger.header('Generating deployment files');

    await fs.ensureDir(this.outputDir);

    // 验证构建产物存在
    await this.verifyBuildArtifacts(config);

    await this.generateDockerfile(config);
    await this.generateNginxConfig(config);
    await this.generateEntrypoint(config);

    logger.success('All files generated');
  }

  /**
   * 验证构建产物存在
   * 这是确保"本地构建优先"原则的关键步骤
   */
  async verifyBuildArtifacts(config) {
    const { project } = config;

    // 验证前端构建产物
    if (project.frontend) {
      const frontendDir = path.join(this.outputDir, 'frontend');
      if (!await fs.pathExists(frontendDir)) {
        throw new Error(
          `前端构建产物不存在: ${frontendDir}\n` +
          `请先运行前端构建命令 (如 npm run build)\n` +
          `注意：Dockerfile 不会在容器内执行构建，必须在本地完成`
        );
      }
      logger.success('前端构建产物验证通过');
    }

    // 验证后端构建产物
    if (project.backend) {
      const backendDir = path.join(this.outputDir, 'backend');
      if (!await fs.pathExists(backendDir)) {
        throw new Error(
          `后端构建产物不存在: ${backendDir}\n` +
          `请先运行后端构建命令 (如 mvn clean package)\n` +
          `注意：Dockerfile 不会在容器内执行构建，必须在本地完成`
        );
      }

      // Java 特殊验证：确保 jar 文件存在
      if (project.backend.runtime === 'java') {
        const jarPath = path.join(backendDir, 'app.jar');
        if (!await fs.pathExists(jarPath)) {
          throw new Error(
            `JAR 文件不存在: ${jarPath}\n` +
            `请先运行: mvn clean package -DskipTests\n` +
            `注意：Dockerfile 不会在容器内执行 mvn 编译，必须在本地完成打包`
          );
        }
        logger.success('JAR 文件验证通过');
      }

      logger.success('后端构建产物验证通过');
    }
  }

  async generateDockerfile(config) {
    logger.step('Generating Dockerfile...');

    const { project, deploy } = config;
    const lines = [];

    // 文件头注释：强调设计原则
    lines.push('# ============================================================');
    lines.push('# Generated by docker-deploy skill');
    lines.push('# ============================================================');
    lines.push('# 重要说明 (IMPORTANT):');
    lines.push('# 1. 此 Dockerfile 只包含运行时环境，不包含应用代码');
    lines.push('# 2. 前后端编译产物通过 volume 挂载到容器内');
    lines.push('# 3. 增量更新时只需替换宿主机 volume 目录中的文件，无需重建镜像');
    lines.push('# 4. 镜像只构建一次，后续发版都是 volume 替换 + 容器重启');
    lines.push('# ============================================================');
    lines.push('');

    // Base image
    lines.push('FROM nginx:alpine');
    lines.push('');

    // Install backend runtime if needed
    if (project.backend) {
      const runtime = this.getRuntimeInstall(project.backend);
      lines.push('# Backend runtime (pre-installed, NOT building in container)');
      lines.push(runtime);
      lines.push('');
    }

    // 前后端代码不 COPY 进镜像，而是通过 volume 挂载
    // 镜像只包含运行时环境 + 配置文件

    // Create volume mount point directories (ensures correct permissions)
    lines.push('# Volume mount points (code is mounted at runtime, NOT baked into image)');
    if (project.frontend) {
      lines.push('RUN mkdir -p /var/www/html && chown -R nginx:nginx /var/www/html');
    }
    if (project.backend) {
      const backendContainerDir = this.getBackendPath(project.backend).container;
      const parentDir = backendContainerDir.replace(/\/[^/]*$/, '');
      lines.push(`RUN mkdir -p ${parentDir}`);
    }
    lines.push('');

    // Logs directory
    lines.push('# Logs directory');
    lines.push('RUN mkdir -p /var/log/nginx');
    if (project.backend) {
      lines.push(`RUN mkdir -p ${this.getBackendLogDir(project.backend)}`);
    }
    lines.push('');

    // Nginx config
    lines.push('# Nginx configuration');
    lines.push('COPY nginx/nginx.conf /etc/nginx/nginx.conf');
    lines.push('');

    // Entrypoint
    lines.push('# Startup script');
    lines.push('COPY scripts/entrypoint.sh /entrypoint.sh');
    lines.push('RUN chmod +x /entrypoint.sh');
    lines.push('');

    // Expose and entrypoint
    lines.push('EXPOSE 80');
    lines.push('ENTRYPOINT ["/entrypoint.sh"]');

    const dockerfile = lines.join('\n');
    await fs.writeFile(path.join(this.outputDir, 'Dockerfile'), dockerfile);
    logger.success('Dockerfile generated');
  }

  getRuntimeInstall(backend) {
    const runtimes = {
      java: this.getJavaRuntimeInstall(backend.jdkVersion),
      node: 'RUN apk add --no-cache nodejs npm',
      python: 'RUN apk add --no-cache python3 py3-pip',
      go: '# Go binary - no runtime needed'
    };
    return runtimes[backend.runtime] || '';
  }

  /**
   * 根据 JDK 版本生成运行时安装命令
   * 包含 fontconfig + 字体，避免验证码等图片生成报错
   */
  getJavaRuntimeInstall(jdkVersion = '17') {
    const jdkPackageMap = {
      '8':  'openjdk8-jre',
      '11': 'openjdk11-jre',
      '17': 'openjdk17-jre',
      '21': 'openjdk21-jre'
    };

    const jdkPackage = jdkPackageMap[jdkVersion] || jdkPackageMap['17'];

    return [
      `# Java runtime (JDK ${jdkVersion}) + fonts, installed to global directory`,
      `RUN apk add --no-cache ${jdkPackage} fontconfig font-dejavu wqy-zenhei && fc-cache -fv`,
    ].join('\n');
  }

  getBackendPath(backend) {
    const paths = {
      java: { file: 'app.jar', container: '/var/app/jar/app.jar' },
      node: { file: '', container: '/var/app/node/' },
      python: { file: '', container: '/var/app/python/' },
      go: { file: 'app', container: '/var/app/go/app' }
    };
    return paths[backend.runtime] || paths.java;
  }

  getBackendLogDir(backend) {
    const dirs = {
      java: '/var/app/jar/logs',
      node: '/var/app/node/logs',
      python: '/var/app/python/logs',
      go: '/var/app/go/logs'
    };
    return dirs[backend.runtime] || '/var/app/logs';
  }

  async generateNginxConfig(config) {
    logger.step('生成 nginx.conf...');

    const { project } = config;
    const lines = [];

    lines.push('worker_processes auto;');
    lines.push('error_log /var/log/nginx/error.log warn;');
    lines.push('pid /var/run/nginx.pid;');
    lines.push('');
    lines.push('events {');
    lines.push('    worker_connections 1024;');
    lines.push('}');
    lines.push('');
    lines.push('http {');
    lines.push('    include /etc/nginx/mime.types;');
    lines.push('    default_type application/octet-stream;');
    lines.push('');
    lines.push('    log_format main \'$remote_addr - $remote_user [$time_local] "$request" \'');
    lines.push('                      \'$status $body_bytes_sent "$http_referer" \'');
    lines.push('                      \'"$http_user_agent" "$http_x_forwarded_for"\';');
    lines.push('');
    lines.push('    access_log /var/log/nginx/access.log main;');
    lines.push('');
    lines.push('    sendfile on;');
    lines.push('    tcp_nopush on;');
    lines.push('    keepalive_timeout 65;');
    lines.push('    gzip on;');
    lines.push('');
    lines.push('    server {');
    lines.push('        listen 80;');
    lines.push('        server_name localhost;');
    lines.push('');

    // Frontend static files
    if (project.frontend) {
      lines.push('        # Frontend static files');
      lines.push('        location / {');
      lines.push('            root /var/www/html;');
      lines.push('            index index.html;');
      lines.push('            try_files $uri $uri/ /index.html;');
      lines.push('        }');
      lines.push('');
    }

    // Proxy locations
    if (project.proxy) {
      lines.push('        # Backend proxy');
      for (const [proxyPath, proxyConfig] of Object.entries(project.proxy)) {
        const port = project.backend?.port || 8080;

        lines.push(`        location ${proxyPath} {`);
        lines.push(`            proxy_pass http://127.0.0.1:${port};`);
        lines.push('            proxy_set_header Host $host;');
        lines.push('            proxy_set_header X-Real-IP $remote_addr;');
        lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
        lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
        lines.push('');
        lines.push('            # 缓冲区设置 - 为大响应和丢包重传留出余地');
        lines.push('            proxy_buffers 16 128k;');
        lines.push('');
        lines.push('            # 超时设置');
        lines.push('            proxy_connect_timeout 60s;');
        lines.push('            proxy_send_timeout 60s;');
        lines.push('            proxy_read_timeout 120s;');
        lines.push('        }');
        lines.push('');
      }
    }

    lines.push('    }');
    lines.push('}');

    const nginxConf = lines.join('\n');
    await fs.ensureDir(path.join(this.outputDir, 'nginx'));
    await fs.writeFile(path.join(this.outputDir, 'nginx', 'nginx.conf'), nginxConf);
    logger.success('nginx.conf 已生成');
  }

  async generateEntrypoint(config) {
    logger.step('生成 entrypoint.sh...');

    const { project } = config;

    const lines = [];

    lines.push('#!/bin/sh');
    lines.push('# Generated by docker-deploy skill');
    lines.push('');
    lines.push('set -e');
    lines.push('');

    // Backend startup
    if (project.backend) {
      lines.push('# Backend startup');
      const startupCmd = this.getBackendStartupCommand(project.backend);
      lines.push(startupCmd);
      lines.push('');
      lines.push('# Wait for backend to start');
      lines.push('sleep 5');
      lines.push('');
      lines.push('# Start Nginx');
      lines.push('echo "Starting Nginx..."');
      lines.push('nginx -g "daemon off;"');
    } else {
      lines.push('# Start Nginx');
      lines.push('echo "Starting Nginx..."');
      lines.push('nginx -g "daemon off;"');
    }

    const entrypoint = lines.join('\n');
    await fs.ensureDir(path.join(this.outputDir, 'scripts'));
    await fs.writeFile(path.join(this.outputDir, 'scripts', 'entrypoint.sh'), entrypoint);
    logger.success('entrypoint.sh 已生成');
  }

  getBackendStartupCommand(backend) {
    const commands = {
      java: `JVM_ARGS="\${JVM_ARGS:--Xmx512m -Xms256m}"
SPRING_PROFILE="\${SPRING_PROFILE:-prod}"

echo "Starting Java application..."
cd /var/app/jar
java $JVM_ARGS -jar app.jar --spring.profiles.active=$SPRING_PROFILE $EXTRA_ARGS &`,
      node: `echo "Starting Node.js application..."
cd /var/app/node
node index.js &`,
      python: `echo "Starting Python application..."
cd /var/app/python
python3 main.py &`,
      go: `echo "Starting Go application..."
cd /var/app/go
./app &`
    };

    return commands[backend.runtime] || commands.java;
  }
}
