// .deploy/scripts/generator.js
import fs from 'fs-extra';
import path from 'path';
import { logger } from './utils/logger.js';
import { DEPLOY_DIR, REMOTE_DIR } from './utils/constants.js';

export class Generator {
  constructor(projectRoot = process.cwd()) {
    this.projectRoot = projectRoot;
    this.outputDir = path.join(projectRoot, DEPLOY_DIR, REMOTE_DIR);
  }

  async generate(config) {
    logger.header('Generating deployment files');

    await fs.ensureDir(this.outputDir);

    await this.generateDockerfile(config);
    await this.generateNginxConfig(config);
    await this.generateEntrypoint(config);

    logger.success('All files generated');
  }

  async generateDockerfile(config) {
    logger.step('Generating Dockerfile...');

    const { project, deploy } = config;
    const lines = [];

    // Base image
    lines.push('# Generated by docker-deploy skill');
    lines.push('FROM nginx:alpine');
    lines.push('');

    // Install backend runtime if needed
    if (project.backend) {
      const runtime = this.getRuntimeInstall(project.backend);
      lines.push('# Backend runtime');
      lines.push(runtime);
      lines.push('');
    }

    // Copy frontend
    if (project.frontend) {
      lines.push('# Frontend static files');
      lines.push('COPY frontend/ /var/www/html/');
      lines.push('');
    }

    // Copy backend
    if (project.backend) {
      lines.push('# Backend application');
      const backendPath = this.getBackendPath(project.backend);
      lines.push(`COPY backend/${backendPath.file} ${backendPath.container}`);
      lines.push('');
    }

    // Logs directory
    lines.push('# Logs directory');
    lines.push('RUN mkdir -p /var/log/nginx');
    if (project.backend) {
      lines.push(`RUN mkdir -p ${this.getBackendLogDir(project.backend)}`);
    }
    lines.push('');

    // Nginx config
    lines.push('# Nginx configuration');
    lines.push('COPY nginx/nginx.conf /etc/nginx/nginx.conf');
    lines.push('');

    // Entrypoint
    lines.push('# Startup script');
    lines.push('COPY scripts/entrypoint.sh /entrypoint.sh');
    lines.push('RUN chmod +x /entrypoint.sh');
    lines.push('');

    // Expose and entrypoint
    lines.push('EXPOSE 80');
    lines.push('ENTRYPOINT ["/entrypoint.sh"]');

    const dockerfile = lines.join('\n');
    await fs.writeFile(path.join(this.outputDir, 'Dockerfile'), dockerfile);
    logger.success('Dockerfile generated');
  }

  getRuntimeInstall(backend) {
    const runtimes = {
      java: 'RUN apk add --no-cache openjdk17-jre-headless',
      node: 'RUN apk add --no-cache nodejs npm',
      python: 'RUN apk add --no-cache python3 py3-pip',
      go: '# Go binary - no runtime needed'
    };
    return runtimes[backend.runtime] || '';
  }

  getBackendPath(backend) {
    const paths = {
      java: { file: 'app.jar', container: '/var/app/jar/app.jar' },
      node: { file: '', container: '/var/app/node/' },
      python: { file: '', container: '/var/app/python/' },
      go: { file: 'app', container: '/var/app/go/app' }
    };
    return paths[backend.runtime] || paths.java;
  }

  getBackendLogDir(backend) {
    const dirs = {
      java: '/var/app/jar/logs',
      node: '/var/app/node/logs',
      python: '/var/app/python/logs',
      go: '/var/app/go/logs'
    };
    return dirs[backend.runtime] || '/var/app/logs';
  }

  async generateNginxConfig(config) {
    // Will be implemented in Task 10
  }

  async generateEntrypoint(config) {
    // Will be implemented in Task 11
  }
}
